name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-central-workflow:
    uses: tu-org/api-operations/.github/workflows/reusable-workflow.yml@main
    with:
      # Define tu lenguaje principal
      language: 'node' 
    secrets: inherit 
